My Pull request for Enumerable Methods
Datagirlcmr/Enumerable-Methods pull request #1
Opened 2019-11-25 17:08 UTC by Datagirlcmr

2019-11-25 23:05 UTC, suretrust requested changes
Hi @Datagirlcmr,

### Great job thus far, :raised_hands: just some suggestions to wrap it up. Please see my comments on your code.

- [ ] Let's set up the linter properly. It should display as shown in the image below:

![linter2](https://user-images.githubusercontent.com/31304943/69585472-19503800-0fe0-11ea-8a65-4ed5c4672eb5.png)

**Kindly submit another code review once these issues have been fixed.** _Happy coding!_ :tada:

2019-11-25 23:05 UTC, suretrust commented on script.rb
> +  end
- [ ] Enumerables my_each returns an Enumerator if no block is given.
`[1,2,3,4,5].my_each` should return `#<Enumerator: [1, 2, 3, 4, 5]:my_each>`

2019-11-25 23:05 UTC, suretrust commented on script.rb
> +  end
- [ ] Enumerables my_each_with_index returns an Enumerator if no block is given
`[1,2,3,4,5].my_each_with_index` should return `#<Enumerator: [1, 2, 3, 4, 5]:my_each_with_index>`

2019-11-25 23:05 UTC, suretrust commented on script.rb
> +  end
- [ ] Enumerables my_select returns an enumerator if no block is given
`p [1,2,3,4,5].my_select` should give `#<Enumerator: [1, 2, 3, 4, 5]:my_select>`

2019-11-25 23:05 UTC, suretrust commented on script.rb
> +  end
- [ ] Enumerables my_all? when no block or argument is given returns true when none of the collection members are false or nil.
`[1,2,3].my_all?` should return `true` since the array doesn't contain `false` or `nil`

- [ ] Enumerables my_all? when a class is passed as an argument returns true if all of the collection is a member of such a class.
`[1,2,3].my_all?(Integer)` should return `true`
`[1,2,'str'].my_all?(Integer)` should return `false`

- [ ] Enumerables my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex
`[1, 2, 3].my_all?(/d/)` should return `false`
- [ ] Enumerables my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

2019-11-25 23:05 UTC, suretrust commented on script.rb
> +
-[ ] Enumerables my_any? when no block or argument is given returns true if at least one of the collection is not false or nil
`[1,false,nil].my_any?` should return `true`

- [ ] Enumerables my_any? when a class is passed as an argument returns true if at least one of the collections is a member of such class.
`['string', 1, 3].my_any?(String)` should return `true`

- [ ] Enumerables my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex

- [ ] Enumerables my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

2019-11-25 23:05 UTC, suretrust commented on script.rb
> +  end
- [ ] Enumerables my_none? when no block or argument is given returns true only if none of the collection members is true.
`[nil, false].my_none?` should return `true`

- [ ] Enumerables my_none? when a class is passed as an argument returns true if none of the collection is a member of such class
`[1,2,3].my_none?(String)` should return `true`

- [ ] Enumerables my_none? when a Regex is passed as an argument returns true only if none of the collection matches the Regex

- [ ] Enumerables my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern

2019-11-25 23:05 UTC, suretrust commented on script.rb
> +
- [ ] Enumerables my_map returns an Enumerator if no block is given.
`p [1,2,3,4,5].my_map` should return `#<Enumerator: [1, 2, 3, 4, 5]:my_map>`

2019-11-25 23:05 UTC, suretrust commented on script.rb
> +    elsif !element.nil?
This code looks similar to `elsif element` double negations is better avoided. `elsif element` returns true just as your code above does.

2019-11-26 12:19 UTC, imhta requested changes
# Require Changes 🛑 

### Hello @Datagirlcmr, 👋 

Your project has some issues with `my_all`, `my_any` and `my_none` methods. Because these are the methods are failing in test. _check the inline comments for more info_

> [Optional] Try to reduce the complexity of a single method. A Method should have single responsibility 

----
### Don't forgot make another code review request
----
#### Happy coding
**Pon Muthu Selvam N**
_If you have any queries ping me in slack 😄_

2019-11-26 12:19 UTC, imhta commented on script.rb
> +  end
### Your `my_all` method are failing in below tests
- [ ] enumerables my_all? returns true if the block never returns false 
or nil
- [ ]  enumerables my_all? when no block or argument is given returns true when none of the collection members are false or nil
- [ ] enumerables my_all? when a class is passed as an argument returns true if all of the collection is a member of such class
- [ ] enumerables my_all? when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [ ] enumerables my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

2019-11-26 12:19 UTC, imhta commented on script.rb
> +  end
### Your `my_any` method are failing in below tests
- [ ] enumerables my_any? returns true if the block ever returns a value other than false or nil
- [ ]  enumerables my_any? when no block or argument is given returns true if at least one of the collection is not false or nil
- [ ] enumerables my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class
- [ ] enumerables my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex
- [ ] enumerables my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern

2019-11-26 12:19 UTC, imhta commented on script.rb
> +  end
### Your `my_none` method are failing in below tests
- [ ]  enumerables my_none? returns true if the block never returns true for all elements
- [ ] enumerables my_none? when no block or argument is given returns true only if none of the collection members is true
- [ ] enumerables my_none? when a class is passed as an argument returns true if none of the collection is a member of such class
- [ ] enumerables my_none? when a Regex is passed as an argument returns true only if none of the collection matches the Regex
- [ ] enumerables my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern

2019-11-26 12:39 UTC, imhta approved these changes
# Project Approved 👍 

### hello @Datagirlcmr , 👋  You have done great job in this project.

<img src="https://thumbs.gfycat.com/SpeedyAmazingIndianpalmsquirrel-size_restricted.gif">

----
### Don't forgot to sumbit project completion form
----

## Keep it up 👏 

**Pon Muthu Selvam N**

2019-11-26 12:48 UTC, merged